version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_APP=src.main
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/crm_python
      - SECRET_KEY=98e15daff0ca359a52be3aafb0a3563b58a0d9a2858cbea89185943d18bff807
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USERNAME=seu_email@gmail.com
      - MAIL_PASSWORD=sua_senha_ou_app_password
      - MAIL_DEFAULT_SENDER=seu_email@gmail.com
      - LINKEDIN_CLIENT_ID=seu_client_id
      - LINKEDIN_CLIENT_SECRET=seu_client_secret
    
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crm_python
    ports:
      - "5432:5432"

volumes:
  postgres_data: